import os

DIV2K_TRAIN_DIR = r"D:\PNG_Dataset\DIV2K_train_HR"
DIV2K_VAL_DIR = r"D:\PNG_Dataset\DIV2K_valid_HR"
FLICKR2K_DIR = r"D:\Flickr2K\Flickr2K_HR"
FLICKR2K_VAL_COUNT = 200

CHAMELEON_REAL_DIR = r"D:\Chameleon\test\0_real"
CHAMELEON_FAKE_DIR = r"D:\Chameleon\test\1_fake"

CALIB_REAL_DIR = None
CALIB_FAKE_DIR = None

IMG_SIZE = 256
IN_CHANNELS = 3
PATCH_SIZE = 16
GRID_SIZE = IMG_SIZE // PATCH_SIZE
NUM_TOKENS = GRID_SIZE * GRID_SIZE
PATCH_DIM = PATCH_SIZE * PATCH_SIZE * IN_CHANNELS

ENC_EMBED_DIM = 384
ENC_DEPTH = 12
ENC_NUM_HEADS = 6
ENC_MLP_RATIO = 4.0
ENC_DROPOUT = 0.0

DEC_EMBED_DIM = 256
DEC_DEPTH = 4
DEC_NUM_HEADS = 8
DEC_MLP_RATIO = 4.0
DEC_DROPOUT = 0.0

TRAIN_MASK_TYPES = ["random", "block"]
TRAIN_MASK_TYPE_PROBS = [0.5, 0.5]
TRAIN_MASK_RATIOS_MAIN = [0.40, 0.60, 0.75]
TRAIN_MASK_RATIOS_AUX = [0.05, 0.10]
TRAIN_MASK_MAIN_PROB = 0.8

EVAL_MASK_TYPES = ["random", "block", "stripe"]
EVAL_MASK_RATIOS = [0.40, 0.50, 0.60, 0.70, 0.75]
EVAL_BASE_MASK_RATIO = 0.10
EVAL_BASE_RUNS = 4
EVAL_K = 8
EVAL_K_LIST = [4, 8, 16]
TAU_PERCENTILE = 5
CORE_EROSION_PX = 8
CORE_MIN_PIXELS = 256
MAX_MASK_SAMPLE_TRIES = 2048

PATCHES_PER_IMAGE = 8
TRAIN_BATCH_SIZE = 16
VAL_BATCH_SIZE = 16
EVAL_BATCH_SIZE = 1
NUM_WORKERS = 4
PIN_MEMORY = True
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 2

EPOCHS = 200
LR = 1e-4
WEIGHT_DECAY = 0.05
GRAD_CLIP = 1.0
WARMUP_EPOCHS = 10

LAMBDA_RAW = 1.0
LAMBDA_LAP = 0.5

VAL_PANEL = [
    ("random", 0.40),
    ("random", 0.60),
    ("random", 0.75),
    ("block", 0.60),
]

THRESHOLD_SEARCH_STEPS = 400
SEED = 42
ENABLE_TF32 = True

EXP_DIR = r"D:\MAE_Test\experiments"
os.makedirs(EXP_DIR, exist_ok=True)
